
INSERT INTO Renter (RenterName, RenterDescription, Bedrooms, Bathrooms, AnimalSupport, SquareFootprint, UnitorStandAlone)
VALUES
('Emily Johnson', 'Quiet and clean tenant', 2, 1, 'Yes', 900, 'Unit'),
('Michael Brown', 'Reliable with on-time payments', 3, 2, 'No', 1200, 'StandAlone'),
('Sarah Davis', 'Friendly and sociable', 1, 1, 'Yes', 800, 'Unit'),
('James Wilson', 'Keeps property well-maintained', 2, 1.5, 'No', 950, 'StandAlone'),
('Jessica Garcia', 'Respectful and quiet', 3, 2, 'Yes', 1300, 'Unit'),
('David Martinez', 'Takes care of property', 2, 1, 'No', 1000, 'StandAlone'),
('Sophia Anderson', 'Neat and orderly', 1, 1, 'Yes', 850, 'Unit'),
('Daniel Taylor', 'Pays rent on time', 3, 2, 'No', 1100, 'StandAlone'),
('Olivia Thomas', 'Good with neighbors', 2, 1.5, 'Yes', 950, 'Unit'),
('Christopher Lee', 'Quiet and respectful', 1, 1, 'No', 750, 'StandAlone'),
('Amelia Harris', 'Keeps property clean', 3, 2, 'Yes', 1400, 'Unit'),
('Matthew Clark', 'Reliable and neat', 2, 1, 'No', 900, 'StandAlone'),
('Isabella Lewis', 'Friendly and responsible', 1, 1, 'Yes', 800, 'Unit'),
('Ethan Robinson', 'Maintains property well', 3, 2, 'No', 1250, 'StandAlone'),
('Mia Walker', 'Quiet and tidy', 2, 1.5, 'Yes', 950, 'Unit'),
('Alexander Young', 'Pays rent promptly', 1, 1, 'No', 750, 'StandAlone'),
('Charlotte Allen', 'Good tenant with pets', 3, 2, 'Yes', 1350, 'Unit'),
('Benjamin King', 'Reliable and orderly', 2, 1, 'No', 900, 'StandAlone'),
('Harper Scott', 'Friendly and neat', 1, 1, 'Yes', 800, 'Unit'),
('William Green', 'Keeps property tidy', 3, 2, 'No', 1200, 'StandAlone'),
('Evelyn Adams', 'Quiet and respectful', 2, 1.5, 'Yes', 950, 'Unit'),
('Mason Hill', 'Pays rent on time', 1, 1, 'No', 750, 'StandAlone'),
('Avery Nelson', 'Reliable and clean', 3, 2, 'Yes', 1300, 'Unit'),
('Elijah Carter', 'Takes care of property', 2, 1, 'No', 1000, 'StandAlone'),
('Abigail Mitchell', 'Friendly and orderly', 1, 1, 'Yes', 800, 'Unit'),
('Logan Perez', 'Maintains property well', 3, 2, 'No', 1250, 'StandAlone'),
('Sofia Roberts', 'Quiet and neat', 2, 1.5, 'Yes', 950, 'Unit'),
('Lucas Turner', 'Pays rent promptly', 1, 1, 'No', 750, 'StandAlone'),
('Ella Phillips', 'Good tenant with pets', 3, 2, 'Yes', 1350, 'Unit'),
('Jack Campbell', 'Reliable and tidy', 2, 1, 'No', 900, 'StandAlone'),
('Chloe Parker', 'Friendly and responsible', 1, 1, 'Yes', 800, 'Unit'),
('Aiden Evans', 'Keeps property clean', 3, 2, 'No', 1400, 'StandAlone'),
('Layla Edwards', 'Quiet and respectful', 2, 1.5, 'Yes', 950, 'Unit'),
('Henry Collins', 'Pays rent on time', 1, 1, 'No', 750, 'StandAlone'),
('Aria Stewart', 'Reliable and neat', 3, 2, 'Yes', 1300, 'Unit'),
('Sebastian Morris', 'Takes care of property', 2, 1, 'No', 1000, 'StandAlone'),
('Mila Sanchez', 'Friendly and tidy', 1, 1, 'Yes', 800, 'Unit'),
('Jackson Rogers', 'Maintains property well', 3, 2, 'No', 1250, 'StandAlone'),
('Zoe Reed', 'Quiet and neat', 2, 1.5, 'Yes', 950, 'Unit'),
('Carter Cook', 'Pays rent promptly', 1, 1, 'No', 750, 'StandAlone'),
('Grace Morgan', 'Good tenant with pets', 3, 2, 'Yes', 1350, 'Unit'),
('Owen Bailey', 'Reliable and tidy', 2, 1, 'No', 900, 'StandAlone'),
('Victoria Murphy', 'Friendly and responsible', 1, 1, 'Yes', 800, 'Unit'),
('Wyatt Rivera', 'Keeps property clean', 3, 2, 'No', 1400, 'StandAlone'),
('Aubrey Cooper', 'Quiet and respectful', 2, 1.5, 'Yes', 950, 'Unit'),
('Dylan Richardson', 'Pays rent on time', 1, 1, 'No', 750, 'StandAlone'),
('Madison Cox', 'Reliable and neat', 3, 2, 'Yes', 1300, 'Unit'),
('Levi Howard', 'Takes care of property', 2, 1, 'No', 1000, 'StandAlone'),
('Lily Ward', 'Friendly and tidy', 1, 1, 'Yes', 800, 'Unit'),
('Caleb Torres', 'Maintains property well', 3, 2, 'No', 1250, 'StandAlone'),
('Hannah Peterson', 'Quiet and neat', 2, 1.5, 'Yes', 950, 'Unit'),
('Nathan Gray', 'Pays rent promptly', 1, 1, 'No', 750, 'StandAlone'),
('Scarlett Ramirez', 'Good tenant with pets', 3, 2, 'Yes', 1350, 'Unit'),
('Isaac James', 'Reliable and tidy', 2, 1, 'No', 900, 'StandAlone'),
('Zoe Price', 'Friendly and responsible', 1, 1, 'Yes', 800, 'Unit'),
('Thomas Brooks', 'Keeps property clean', 3, 2, 'No', 1400, 'StandAlone'),
('Savannah Kelly', 'Quiet and respectful', 2, 1.5, 'Yes', 950, 'Unit'),
('Samuel Sanders', 'Pays rent on time', 1, 1, 'No', 750, 'StandAlone'),
('Brooklyn Flores', 'Reliable and neat', 3, 2, 'Yes', 1300, 'Unit'),
('Isaiah Morris', 'Takes care of property', 2, 1, 'No', 1000, 'StandAlone'),
('Leah Russell', 'Friendly and tidy', 1, 1, 'Yes', 800, 'Unit'),
('Gabriel Diaz', 'Maintains property well', 3, 2, 'No', 1250, 'StandAlone'),
('Victoria Edwards', 'Quiet and neat', 2, 1.5, 'Yes', 950, 'Unit'),
('Lincoln Butler', 'Pays rent promptly', 1, 1, 'No', 750, 'StandAlone'),
('Hazel Bailey', 'Good tenant with pets', 3, 2, 'Yes', 1350, 'Unit'),
('Anthony Ward', 'Reliable and tidy', 2, 1, 'No', 900, 'StandAlone'),
('Eleanor Gray', 'Friendly and responsible', 1, 1, 'Yes', 800, 'Unit'),
('Eli Price', 'Keeps property clean', 3, 2, 'No', 1400, 'StandAlone'),
('Paisley Brooks', 'Quiet and respectful', 2, 1.5, 'Yes', 950, 'Unit'),
('Josiah Sanders', 'Pays rent on time', 1, 1, 'No', 750, 'StandAlone'),
('Penelope Kelly', 'Reliable and neat', 3, 2, 'Yes', 1300, 'Unit'),
('David Flores', 'Takes care of property', 2, 1, 'No', 1000, 'StandAlone'),
('Ariana Morgan', 'Friendly and tidy', 1, 1, 'Yes', 800, 'Unit'),
('Hudson James', 'Maintains property well', 3, 2, 'No', 1250, 'StandAlone'),
('Violet Richardson', 'Quiet and neat', 2, 1.5, 'Yes', 950, 'Unit'),
('John Ramirez', 'Pays rent promptly', 1, 1, 'No', 750, 'StandAlone'),
('Ruby Martinez', 'Good tenant with pets', 3, 2, 'Yes', 1350, 'Unit'),
('Hunter Lee', 'Reliable and tidy', 2, 1, 'No', 900, 'StandAlone'),
('Isabelle Anderson', 'Friendly and responsible', 1, 1, 'Yes', 800, 'Unit'),
('Isaac Scott', 'Keeps property clean', 3, 2, 'No', 1400, 'StandAlone'),
('Grace Harris', 'Quiet and respectful', 2, 1.5, 'Yes', 950, 'Unit'),
('Maverick Allen', 'Pays rent on time', 1, 1, 'No', 750, 'StandAlone'),
('Anna Robinson', 'Reliable and neat', 3, 2, 'Yes', 1300, 'Unit'),
('Joseph Lewis', 'Takes care of property', 2, 1, 'No', 1000, 'StandAlone'),
('Aurora Green', 'Friendly and tidy', 1, 1, 'Yes', 800, 'Unit'),
('Santiago Thomas', 'Maintains property well', 3, 2, 'No', 1250, 'StandAlone'),
('Addison Young', 'Quiet and neat', 2, 1.5, 'Yes', 950, 'Unit'),
('Ryan Martinez', 'Pays rent promptly', 1, 1, 'No', 750, 'StandAlone'),
('Bella Johnson', 'Good tenant with pets', 3, 2, 'Yes', 1350, 'Unit'),
('Julian Brown', 'Reliable and tidy', 2, 1, 'No', 900, 'StandAlone'),
('Riley Davis', 'Friendly and responsible', 1, 1, 'Yes', 800, 'Unit');


SELECT COUNT(*) FROM Renter;
