
INSERT INTO Review (RenterId, PropertyId, Rating, ReviewText)
VALUES

(1, 1, 4, 'Great location and amenities.'),
(2, 2, 5, 'Spacious and well-maintained property.'),
(3, 3, 3, 'Noisy neighbors but otherwise good.'),
(4, 4, 4, 'Clean and comfortable.'),
(5, 5, 2, 'Issues with plumbing.'),
(6, 6, 5, 'Perfect place for families.'),
(7, 7, 4, 'Nice community, convenient location.'),
(8, 8, 3, 'Could use better maintenance.'),
(9, 9, 5, 'Excellent property management.'),
(10, 10, 4, 'Quiet and peaceful neighborhood.'),
(11, 11, 2, 'Old appliances need upgrading.'),
(12, 12, 5, 'Beautiful view from the balcony.'),
(13, 13, 4, 'Responsive landlord, minor repairs needed.'),
(14, 14, 3, 'Close to amenities but noisy.'),
(15, 15, 5, 'Very satisfied with the property.'),
(16, 16, 4, 'Comfortable living space.'),
(17, 17, 3, 'Average property, good location.'),
(18, 18, 5, 'Love the pet-friendly policy.'),
(19, 19, 4, 'Spacious rooms, good natural light.'),
(20, 20, 2, 'Poor heating system in winter.'),
(21, 21, 5, 'Well-maintained grounds.'),
(22, 22, 4, 'Friendly neighbors.'),
(23, 23, 3, 'Limited parking space.'),
(24, 24, 5, 'Great community amenities.'),
(25, 25, 4, 'Responsive maintenance team.'),
(26, 26, 3, 'Average property condition.'),
(27, 27, 5, 'Excellent location.'),
(28, 28, 4, 'Quiet and peaceful environment.'),
(29, 29, 3, 'Issues with plumbing.'),
(30, 30, 5, 'Beautiful views.'),
(31, 31, 4, 'Clean and well-maintained property.'),
(32, 32, 3, 'Good location but noisy at times.'),
(33, 33, 5, 'Friendly and helpful property manager.'),
(34, 34, 4, 'Modern amenities.'),
(35, 35, 3, 'Could use better upkeep.'),
(36, 36, 5, 'Great place to live.'),
(37, 37, 4, 'Comfortable living space.'),
(38, 38, 3, 'Average property, convenient location.'),
(39, 39, 5, 'Well-managed property.'),
(40, 40, 4, 'Quiet neighborhood, good schools nearby.'),
(41, 41, 3, 'Needs updates in kitchen and bathrooms.'),
(42, 42, 5, 'Love the community activities.'),
(43, 43, 4, 'Responsive maintenance team.'),
(44, 44, 3, 'Decent place to live.'),
(45, 45, 5, 'Great amenities.'),
(46, 46, 4, 'Nice location.'),
(47, 47, 3, 'Average property condition.'),
(48, 48, 5, 'Excellent property management.'),
(49, 49, 4, 'Clean and comfortable.'),
(50, 50, 3, 'Issues with noise pollution.'),


(1, 51, 4, 'Excellent location, convenient for commuting.'),
(2, 52, 5, 'Love the spacious layout.'),
(3, 53, 3, 'Noisy neighbors are a downside.'),
(4, 54, 4, 'Clean and well-maintained property.'),
(5, 55, 2, 'Plumbing issues need attention.'),
(6, 56, 5, 'Great amenities for families.'),
(7, 57, 4, 'Convenient location with good access.'),
(8, 58, 3, 'Maintenance could be more responsive.'),
(9, 59, 5, 'Professional property management.'),
(10, 60, 4, 'Peaceful neighborhood.'),
(11, 61, 2, 'Appliances are outdated.'),
(12, 62, 5, 'Scenic views from the apartment.'),
(13, 63, 4, 'Landlord is quick to address issues.'),
(14, 64, 3, 'Noisy area but close to amenities.'),
(15, 65, 5, 'Highly satisfied with the property.'),
(16, 66, 4, 'Comfortable and cozy living space.'),
(17, 67, 3, 'Average property condition.'),
(18, 68, 5, 'Pet-friendly policies are a plus.'),
(19, 69, 4, 'Spacious rooms and good natural lighting.'),
(20, 70, 2, 'Heating system needs improvement.'),
(21, 71, 5, 'Well-kept grounds and facilities.'),
(22, 72, 4, 'Friendly neighborhood atmosphere.'),
(23, 73, 3, 'Limited parking availability.'),
(24, 74, 5, 'Great amenities and community features.'),
(25, 75, 4, 'Responsive maintenance service.'),
(26, 76, 3, 'Property upkeep could be better.'),
(27, 77, 5, 'Excellent location for convenience.'),
(28, 78, 4, 'Quiet and serene environment.'),
(29, 79, 3, 'Frequent plumbing issues.'),
(30, 80, 5, 'Beautiful views from the property.'),
(31, 81, 4, 'Well-maintained and clean property.'),
(32, 82, 3, 'Good location but occasional noise disturbances.'),
(33, 83, 5, 'Helpful and friendly property management.'),
(34, 84, 4, 'Modern amenities and facilities.'),
(35, 85, 3, 'Property could use more maintenance.'),
(36, 86, 5, 'Overall great living experience.'),
(37, 87, 4, 'Comfortable and pleasant living space.'),
(38, 88, 3, 'Average property condition, good location.'),
(39, 89, 5, 'Efficient property management.'),
(40, 90, 4, 'Quiet neighborhood with good schools nearby.'),
(41, 91, 3, 'Outdated kitchen and bathroom features.'),
(42, 92, 5, 'Community events and activities are enjoyable.'),
(43, 93, 4, 'Prompt response from maintenance team.'),
(44, 94, 3, 'Decent place to reside.'),
(45, 95, 5, 'Great amenities and services.'),
(46, 96, 4, 'Nice location with convenient access.'),
(47, 97, 3, 'Average property condition.'),
(48, 98, 5, 'Excellent property management services.'),
(49, 99, 4, 'Clean and comfortable living environment.'),
(50, 100, 3, 'Noise pollution can be bothersome.');

SELECT COUNT(*) FROM Review;
